INSERT INTO Airports (Name, MaxCapacityRunway, MaxCapacityWarehouse, City)
VALUES
('John F. Kennedy International Airport', 34, 70, 'New York'),
('Los Angeles International Airport', 20, 45, 'Los Angeles'),
('Heathrow Airport', 45, 60, 'London'),
('Tokyo Haneda Airport', 15, 35, 'Tokyo'),
('Sydney Kingsford Smith Airport', 15, 28, 'Sydney'),
('Paris Charles de Gaulle Airport', 18, 32, 'Paris'),
('Dubai International Airport', 25, 38, 'Dubai'),
('Beijing Capital International Airport', 58, 83, 'Beijing'),
('O´Hare International Airport', 52, 36, 'Chicago'),
('Frankfurt Airport', 27, 69, 'Frankfurt'),
('Changi Airport', 32, 84, 'Singapore'),
('Incheon International Airport', 16, 41, 'Incheon'),
('Amsterdam Schiphol Airport', 19, 27, 'Amsterdam'),
('Hartsfield-Jackson Atlanta International Airport', 53, 39, 'Atlanta'),
('Denver International Airport', 17, 26, 'Denver'),
('San Francisco International Airport', 19, 37, 'San Francisco'),
('Beirut-Rafic Hariri International Airport', 42, 22, 'Beirut'),
('Copenhagen Airport', 46, 24, 'Copenhagen'),
('Mumbai Chhatrapati Shivaji Maharaj International Airport', 61, 32, 'Mumbai'),
('Barcelona-El Prat Airport', 50, 26, 'Barcelona'),
('Toronto Pearson International Airport', 48, 28, 'Toronto'),
('Moscow Sheremetyevo International Airport', 54, 30, 'Moscow'),
('Stockholm Arlanda Airport', 17, 29, 'Stockholm'),
('Dublin Airport', 13, 23, 'Dublin'),
('Seoul Gimpo International Airport', 29, 27, 'Seoul'),
('Hong Kong International Airport', 27, 33, 'Hong Kong'),
('Vienna International Airport', 22, 31, 'Vienna'),
('Zurich Airport', 15, 34, 'Zurich'),
('Madrid Adolfo Suárez Madrid–Barajas Airport', 18, 35, 'Madrid'),
('Brussels Airport', 14, 25, 'Brussels'),
('Amman Queen Alia International Airport', 41, 21, 'Amman'),
('Oslo Gardermoen Airport', 13, 36, 'Oslo'),
('Istanbul Atatürk Airport', 26, 37, 'Istanbul'),
('Kuala Lumpur International Airport', 51, 38, 'Kuala Lumpur'),
('Auckland Airport', 19, 39, 'Auckland'),
('Johannesburg O.R. Tambo International Airport', 45, 40, 'Johannesburg'),
('Munich Airport', 10, 41, 'Munich'),
('Bangkok Suvarnabhumi Airport', 12, 42, 'Bangkok'),
('São Paulo/Guarulhos–Governador André Franco Montoro International Airport', 65, 43, 'São Paulo'),
('Shanghai Pudong International Airport', 17, 44, 'Shanghai'),
('Helsinki-Vantaa Airport', 10, 25, 'Helsinki'),
('Prague Václav Havel Airport', 55, 32, 'Prague'),
('Warsaw Chopin Airport', 13, 30, 'Warsaw'),
('Doha Hamad International Airport', 18, 33, 'Doha'),
('Rome Leonardo da Vinci–Fiumicino Airport', 18, 28, 'Rome'),
('Budapest Ferenc Liszt International Airport', 21, 31, 'Budapest'),
('Athens Eleftherios Venizelos International Airport', 7, 9, 'Athens'),
('Cairo International Airport', 14, 26, 'Cairo'),
('Singapore Changi Airport', 12, 37, 'Singapore'),
('Kolkata Netaji Subhas Chandra Bose International Airport', 9, 27, 'Kolkata'),
('Lisbon Humberto Delgado Airport', 54, 31, 'Lisbon'),
('Hamburg Airport', 16, 29, 'Hamburg'),
('Manila Ninoy Aquino International Airport', 56, 35, 'Manila'),
('Cape Town International Airport', 12, 25, 'Cape Town'),
('Geneva Airport', 12, 30, 'Geneva'),
('Colombo Bandaranaike International Airport', 59, 36, 'Colombo'),
('Melbourne Tullamarine Airport', 10, 28, 'Melbourne'),
('Edinburgh Airport', 18, 26, 'Edinburgh'),
('Casablanca Mohammed V International Airport', 15, 24, 'Casablanca'),
('Hanoi Noi Bai International Airport', 14, 33, 'Hanoi'),
('Vancouver International Airport', 19, 35, 'Vancouver'),
('Perth Airport', 17, 30, 'Perth'),
('Franjo Tuđman Airport', 15, 30, 'Zagreb'),
('Split Airport', 10, 25, 'Split'),
('Dubrovnik Airport', 8, 20, 'Dubrovnik'),
('Rijeka Airport', 5, 18, 'Rijeka'),
('Zadar Airport', 7, 19, 'Zadar'),
('Pula Airport', 16, 21, 'Pula'),
('Osijek Airport', 3, 16, 'Osijek'),
('Sunset Bay International Airport', 28, 42, 'Sunset Bay'),
('Mountain Vista Airfield', 20, 35, 'Mountain Vista'),
('Azure Skies Regional Airport', 24, 38, 'Azure Skies'),
('Mystic Valley Airstrip', 18, 30, 'Mystic Valley'),
('Emerald City Air Terminal', 26, 40, 'Emerald City'),
('Sapphire Ridge International Airport', 30, 45, 'Sapphire Ridge'),
('Whispering Pines Aerodrome', 22, 32, 'Whispering Pines'),
('Golden Sands Skyport', 25, 36, 'Golden Sands'),
('Crystal Lake Landing Strip', 16, 28, 'Crystal Lake'),
('Starlight Haven Airfield', 21, 34, 'Starlight Haven'),
('Wildflower Meadow Airport', 23, 37, 'Wildflower Meadow'),
('Silver Peak Airstrip', 19, 33, 'Silver Peak'),
('Aurora Borealis Airbase', 27, 39, 'Aurora Borealis'),
('Diamond Sky Airfield', 38, 42, 'Crystal City'),
('AeroMeadows Landing Zone', 20, 25, 'Meadowville'),
('Celestial Heights Airstrip', 32, 36, 'Skytopia'),
('Harmony Valley Airbase', 18, 22, 'Tranquil Town'),
('Whirlwind Air Haven', 24, 30, 'Breezeville'),
('Pinnacle Peak Airstrip', 15, 18, 'Summit Springs'),
('AeroDunes Oasis Airfield', 28, 32, 'Desert Oasis'),
('Sunny Skies Landing Pad', 22, 26, 'Sunshine City'),
('Evergreen Ridge Air Terminal', 30, 38, 'Greenwood'),
('Moonlight Bay Skyport', 7, 13, 'Lunar Harbor'),
('AeroVista Serenity Landing', 23, 28, 'Calm Cove'),
('AstraGrove Skyfield', 25, 30, 'Starlight Grove'),
('Blossom Breeze Airstrip', 19, 24, 'Floral Fields'),
('Eagles Nest Air Hub', 21, 26, 'Highland Haven'),
('Whispering Winds Airbase', 32, 37, 'Zephyr Heights'),
('Tranquil Twilight Landing', 9, 24, 'Dusk Valley'),
('Zenith Skies Aerodrome', 35, 39, 'Zenith City'),
('Elysium Heights Landing Zone', 16, 20, 'Heavenly Heights');

INSERT INTO Airplanes (Status, Location, PassengerCapacity, AirportID, Name, Model, Company) 
VALUES 
('Active', 'Warehouse', 129, 11, 'ZenithZoomer', 'Boeing', 'Lufthansa'),
('Disassembled', 'Warehouse', 86, 96, 'SkySprinter', 'Cessna', 'Emirates'),
('Active', 'Air', 58, 71, 'AeroAlchemy', 'Embraer', 'CelestialCentaur Airways'),
('Active', 'Air', 129, 76, 'AerolineaMaxima', 'Airbus', 'QuantumQuasar Airways'),
('Disassembled', 'Warehouse', 111, 34, 'AeroPhoenix', 'Cessna', 'CelestialChariot Airlines'),
('Active', 'Runway', 46, 62, 'GalaxyGlider', 'Boeing', 'NebulaNightingale Travels'),
('Disassembled', 'Warehouse', 116, 15, 'AuroraExpress', 'Embraer', 'StratosStar Airlines'),
('Under Repair', 'Warehouse', 12, 72, 'NimbusNemesis', 'Boeing', 'CelestialCygnet Airways'),
('For Sale', 'Warehouse', 120, 18, 'SolarisSeraphim', 'Bombardier', 'NimbusNebula Flights'),
('Under Repair', 'Warehouse', 128, 98, 'NebulaNightingale', 'Airbus', 'NimbusNomad Airlines'),
('Under Repair', 'Warehouse', 114, 53, 'AeroPioneer', 'Embraer', 'QuantumQuasar Airways'),
('For Sale', 'Warehouse', 146, 51, 'SolarFlareFlyer', 'Cessna', 'NimbusNemesis Travels'),
('For Sale', 'Warehouse', 43, 39, 'AuroraAtlas', 'Embraer', 'AeroAlchemy Airways'),
('Active', 'Air', 118, 45, 'StratosSprinter', 'Bombardier', 'QuantumQuiver Airways'),
('Under Repair', 'Warehouse', 127, 47, 'CelestialCruiser', 'Bombardier', 'United Airlines'),
('Disassembled', 'Warehouse', 38, 65, 'AeroAlchemy', 'Boeing', 'SkywardSpectra Airlines'),
('Active', 'Runway', 93, 47, 'CelestialCassiopeia', 'Cessna', 'Emirates'),
('Active', 'Runway', 98, 36, 'ZenithZoomer', 'Bombardier', 'AeroNautica Express'),
('Disassembled', 'Warehouse', 91, 39, 'NimbusNomad', 'Airbus', 'United Airlines'),
('Under Repair', 'Warehouse', 131, 17, 'SkyPinnacle', 'Cessna', 'CelestialChariot Airlines'),
('Active', 'Air', 66, 31, 'SolarisSeraphim', 'Boeing', 'Delta Airlines'),
('Active', 'Air', 49, 41, 'NimbusNemesis', 'Bombardier', 'AeroAlchemy Airways'),
('Disassembled', 'Warehouse', 13, 14, 'ZenithZephyr', 'Boeing', 'StratosSerpent Airlines'),
('For Sale', 'Warehouse', 99, 84, 'CelestialChariot', 'Cessna', 'HorizonHarbor Airways'),
('Active', 'Runway', 126, 97, 'AuroraAether', 'Boeing', 'StratosSerpent Airlines'),
('Under Repair', 'Warehouse', 62, 62, 'CelestialComet', 'Airbus', 'SolarisSeraphim Flights'),
('Active', 'Runway', 72, 38, 'NimbusNighthawk', 'Embraer', 'VelocityVortex Voyages'),
('For Sale', 'Warehouse', 102, 24, 'NimbusNighthawk', 'Cessna', 'SolarSovereign Airlines'),
('Disassembled', 'Warehouse', 91, 22, 'ZenithZephyr', 'Embraer', 'AeroNautica Express'),
('Active', 'Air', 83, 83, 'HorizonHawk', 'Boeing', 'CelestialCygnet Airways'),
('For Sale', 'Warehouse', 108, 10, 'StratosStargazer', 'Embraer', 'StellarSky Airlines'),
('For Sale', 'Warehouse', 30, 19, 'AuroraAtlas', 'Airbus', 'StratosSagittarius Airlines'),
('Active', 'Runway', 70, 34, 'QuantumQuasar', 'Cessna', 'United Airlines'),
('Active', 'Warehouse', 31, 40, 'StratosSagittarius', 'Bombardier', 'AltitudeAdventures'),
('Under Repair', 'Warehouse', 68, 36, 'NebulaNightingale', 'Boeing', 'SkywardSpectra Airlines'),
('Active', 'Runway', 87, 59, 'EquinoxEagle', 'Bombardier', 'StratosSerpent Airlines'),
('Active', 'Runway', 135, 52, 'AeroAlchemy', 'Bombardier', 'British Airways'),
('Active', 'Air', 81, 19, 'OrionOzymandias', 'Bombardier', 'AuroraAtlas Flights'),
('Under Repair', 'Warehouse', 26, 6, 'AltitudeAurora', 'Boeing', 'HorizonJet Airways'),
('Active', 'Air', 11, 54, 'SolarSovereign', 'Cessna', 'Qatar Airways'),
('For Sale', 'Warehouse', 104, 31, 'AltitudeAurora', 'Airbus', 'QuantumQuasar Aviation'),
('For Sale', 'Runway', 88, 12, 'InfinityInferno', 'Airbus', 'OrionOblivion Travels'),
('Active', 'Runway', 102, 7, 'OrionOzymandias', 'Cessna', 'QuantumQuasar Airways'),
('Active', 'Runway', 76, 22, 'VelocityVimana', 'Boeing', 'CelestialCentaur Airways'),
('Disassembled', 'Warehouse', 72, 30, 'CelestialChaser', 'Bombardier', 'VelocityVimana Airlines'),
('Active', 'Air', 102, 33, 'StratosSagittarius', 'Embraer', 'AeroNautica Express'),
('Active', 'Air', 38, 12, 'QuantumQuasar', 'Bombardier', 'AeroAlchemy Airways'),
('For Sale', 'Runway', 56, 26, 'AuroraAether', 'Boeing', 'Southwest Airlines'),
('For Sale', 'Warehouse', 23, 63, 'AuroraAviator', 'Embraer', 'InfinityInferno Airways'),
('Disassembled', 'Warehouse', 65, 10, 'ZenithZephyr', 'Cessna', 'American Airlines'),
('For Sale', 'Warehouse', 48, 37, 'StellarSurfer', 'Boeing', 'QuantumQuasar Aviation'),
('For Sale', 'Warehouse', 55, 32, 'ZenithZephyr', 'Airbus', 'NebulaNomad Airways'),
('For Sale', 'Warehouse', 26, 17, 'VelocityVortex', 'Bombardier', 'AuroraAlbatross Travels'),
('For Sale', 'Runway', 82, 91, 'HorizonVoyager', 'Embraer', 'NebulaNectar Aviation'),
('Disassembled', 'Warehouse', 92, 40, 'VelocityVortex', 'Boeing', 'SkyPinnacle Airlines'),
('Active', 'Runway', 115, 54, 'SolarSailor', 'Cessna', 'StratosSerpent Airlines'),
('Active', 'Runway', 146, 17, 'AeroAegis', 'Airbus', 'NebulaNomad Airways'),
('Active', 'Air', 88, 10, 'QuantumQuasar', 'Cessna', 'QuantumQuest Air'),
('Under Repair', 'Warehouse', 143, 54, 'SolarisSphinx', 'Airbus', 'British Airways'),
('Under Repair', 'Warehouse', 84, 27, 'StratosSerpent', 'Cessna', 'CelestialCassiopeia Flights'),
('Disassembled', 'Warehouse', 121, 32, 'GalaxyGlider', 'Embraer', 'AuroraAero Services'),
('Active', 'Air', 88, 26, 'VelocityVortex', 'Embraer', 'QuantumQuasar Airways'),
('Active', 'Air', 56, 40, 'NimbusNomad', 'Boeing', 'AeroNautica Express'),
('Active', 'Warehouse', 80, 13, 'InfinityInterceptor', 'Airbus', 'HorizonHawk Airlines'),
('For Sale', 'Warehouse', 130, 7, 'VelocityVimana', 'Bombardier', 'QuantumQuasar Airways'),
('Active', 'Air', 99, 69, 'NebulaNightingale', 'Cessna', 'AeroAegis International'),
('For Sale', 'Warehouse', 147, 44, 'AuroraAtlas', 'Boeing', 'StellarSurfer Flights'),
('Active', 'Runway', 39, 47, 'StratosStargazer', 'Bombardier', 'ZenithZodiac Travels'),
('Active', 'Air', 109, 77, 'InfinityInterceptor', 'Boeing', 'InfinityAir Travels'),
('Under Repair', 'Warehouse', 117, 21, 'VelocityVista', 'Boeing', 'InfinityInferno Airways'),
('Active', 'Runway', 10, 9, 'CelestialChariot', 'Airbus', 'AeroAlchemy Airways'),
('Active', 'Runway', 38, 64, 'SolarWing', 'Embraer', 'OrionOzymandias Airways'),
('Active', 'Warehouse', 60, 9, 'StratosSagittarius', 'Embraer', 'StellarSky Airlines'),
('For Sale', 'Warehouse', 88, 37, 'NimbusNomad', 'Boeing', 'CelestialCygnet Airways'),
('Active', 'Runway', 48, 25, 'NimbusJet', 'Boeing', 'NimbusNebula Flights'),
('Under Repair', 'Warehouse', 17, 20, 'ZenithZephyr', 'Embraer', 'NimbusNemesis Travels'),
('For Sale', 'Warehouse', 57, 52, 'AuroraAlbatross', 'Boeing', 'CelestialCassiopeia Flights'),
('For Sale', 'Warehouse', 24, 77, 'VelocityVimana', 'Boeing', 'NimbusNautical'),
('Active', 'Runway', 50, 8, 'AeroAlchemy', 'Cessna', 'QuantumQuasar Aviation'),
('Active', 'Runway', 69, 1, 'StratosSagittarius', 'Boeing', 'SkywardSpectra Airlines'),
('Active', 'Runway', 122, 2, 'QuantumQuest', 'Airbus', 'CelestialAir'),
('Under Repair', 'Warehouse', 79, 11, 'StellarSurfer', 'Embraer', 'AeroAegis Airways'),
('For Sale', 'Warehouse', 143, 20, 'SkywardSpectacle', 'Boeing', 'Delta Airlines'),
('Disassembled', 'Warehouse', 146, 43, 'SkywardSpectacle', 'Airbus', 'QuantumQuasar Airways'),
('Active', 'Air', 79, 38, 'International', 'Boeing', 'QuantumQuiver Airways'),
('Under Repair', 'Warehouse', 71, 49, 'StarGlider', 'Embraer', 'StellarSky Airlines'),
('For Sale', 'Warehouse', 135, 48, 'NebulaNomad', 'Airbus', 'SolarisSkyline'),
('Active', 'Runway', 15, 48, 'NebulaNavigator', 'Embraer', 'SolarisSeraphim Flights'),
('Active', 'Warehouse', 150, 44, 'SolarFlareFlyer', 'Bombardier', 'Emirates'),
('Active', 'Runway', 80, 22, 'NebulaNightingale', 'Embraer', 'QuantumQuasar Aviation'),
('Active', 'Air', 119, 25, 'OrionOdyssey', 'Airbus', 'SkywardSpectra Airlines'),
('Active', 'Runway', 46, 25, 'QuantumQuasar', 'Cessna', 'NimbusNomad Airlines'),
('Active', 'Air', 32, 17, 'AeroAegis', 'Embraer', 'NimbusNemesis Travels'),
('Active', 'Air', 110, 32, 'SolarFlareFlyer', 'Bombardier', 'CelestialCentaur Airways'),
('Active', 'Warehouse', 16, 34, 'StellarSurfer', 'Embraer', 'QuantumQuasar Airways'),
('Under Repair', 'Warehouse', 87, 39, 'NimbusJet', 'Boeing', 'QuantumQuest Air'),
('Disassembled', 'Warehouse', 103, 21, 'OrionOutrider', 'Bombardier', 'GalaxyGlider Airlines'),
('For Sale', 'Warehouse', 61, 12, 'GalaxyGlider', 'Embraer', 'United Airlines'),
('Active', 'Runway', 86, 34, 'SkyPioneer', 'Airbus', 'British Airways'),
('Active', 'Air', 99, 37, 'SolarFlareFlyer', 'Cessna', 'British Airways'),
('Active', 'Air', 148, 21, 'VelocityVortex', 'Cessna', 'CelestialCentaur Airways'),
('Active', 'Runway', 69, 23, 'StratosSagittarius', 'Boeing', 'StratosStar Airlines');